import { PACKAGE_LEVELS } from './data.js';
import { downloadBackup, loadData, resetData, saveData } from './storage.js';

let data = loadData();
let tab = 'packages';
let search = '';
let categoryFilter = 'all';
const root = document.querySelector('#admin-app');
const esc = (v = '') => String(v).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uid = p => `${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const lines = v => String(v || '').split('\n').map(x => x.trim()).filter(Boolean);
const join = v => Array.isArray(v) ? v.join('\n') : '';
const slotsText = v => Array.isArray(v) ? v.map(s => [s.label,s.boardingTime,s.sailingTime,s.returnTime,s.days].join(' | ')).join('\n') : '';
const slotsParse = v => lines(v).map((x,i) => { const [label='Trip',boardingTime='',sailingTime='',returnTime='',days='Daily'] = x.split('|').map(y=>y.trim()); return {id:uid(`slot-${i}`),label,boardingTime,sailingTime,returnTime,days}; });
const faqText = v => Array.isArray(v) ? v.map(x => `${x.question} | ${x.answer}`).join('\n') : '';
const faqParse = v => lines(v).map(x => { const [question='', ...rest] = x.split('|'); return {question:question.trim(),answer:rest.join('|').trim()}; }).filter(x=>x.question);
const persist = (message='Saved') => { data = saveData(data); toast(message); render(); };

function toast(message){ let el=document.querySelector('#cms-toast'); if(!el){el=document.createElement('div');el.id='cms-toast';el.className='toast';document.body.append(el);} el.textContent=message;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1600); }
function sidebar(){ const tabs=[['packages','▣','Packages'],['categories','▤','Categories'],['addons','＋','Add-ons'],['sections','☷','Page Sections'],['navigation','↗','Navigation'],['settings','⚙','Site Settings'],['backup','⇩','Backup']]; return `<aside class="admin-sidebar"><div class="admin-brand"><span>G</span><div><strong>Get Your Guide</strong><small>Private CMS</small></div></div>${tabs.map(([id,icon,label])=>`<button data-tab="${id}" class="${tab===id?'active':''}"><span>${icon}</span>${label}</button>`).join('')}<a href="/" target="_blank" rel="noopener">View public website</a></aside>`; }
function topbar(){ return `<header class="admin-top"><div><span class="eyebrow">Hidden content management</span><h1>${esc(tab[0].toUpperCase()+tab.slice(1))}</h1></div><div><span class="saved-indicator">${data.updatedAt?'Saved data':'Draft data'}</span><button class="primary" id="save-all">Save all</button></div></header>`; }
function stat(){ const complete=data.packages.filter(p=>p.description&&p.inclusions?.length&&p.paymentMethod&&p.faqs?.length).length; return `<div class="admin-dashboard"><div class="stat-card"><span>Total packages</span><strong>${data.packages.length}</strong><small>${data.packages.filter(p=>p.visible).length} visible</small></div><div class="stat-card"><span>Complete details</span><strong>${complete}</strong><small>Package content populated</small></div><div class="stat-card"><span>Add-ons</span><strong>${data.addOns.length}</strong><small>Reusable upgrades</small></div><div class="stat-card"><span>Sections</span><strong>${data.sections.length}</strong><small>Header to footer</small></div></div>`; }
function packages(){ const cats=data.categories; const list=data.packages.filter(p=>(categoryFilter==='all'||p.categoryId===categoryFilter)&&(!search||`${p.title} ${p.level} ${p.location}`.toLowerCase().includes(search))); return `${stat()}<div class="admin-list cms-list"><div class="list-head"><div><h2>Complete package CMS</h2><p>Edit every public package field. Changes save to this browser draft.</p></div><button class="primary" data-create="package">＋ Create package</button></div><div class="cms-filters"><input id="package-search" placeholder="Search packages" value="${esc(search)}"><select id="category-filter"><option value="all">All categories</option>${cats.map(c=>`<option value="${esc(c.id)}" ${c.id===categoryFilter?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div>${list.sort((a,b)=>a.order-b.order).map(p=>packageRow(p)).join('')||'<p>No packages found.</p>'}</div>`; }
function packageRow(p){ const cat=data.categories.find(c=>c.id===p.categoryId); const complete=[p.description,p.buffetDetails,p.paymentMethod,p.cancellationPolicy,p.faqs?.length].filter(Boolean).length; return `<article class="admin-row cms-package-row" data-id="${esc(p.id)}"><div><strong>${esc(p.title)}</strong><small>${esc(cat?.name||'')} · ${esc(p.level)} · AED ${Number(p.offerPrice||0).toLocaleString()} · ${complete}/5 detail groups</small></div><span class="status ${p.visible?'visible':'hidden'}">${p.visible?'Visible':'Hidden'}</span><div class="row-actions"><button data-action="preview" title="Preview">↗</button><button data-action="up">↑</button><button data-action="down">↓</button><button data-action="duplicate">⧉</button><button data-action="toggle">${p.visible?'◉':'○'}</button><button data-action="edit">✎</button><button class="danger-icon" data-action="delete">⌫</button></div></article>`; }
function genericList(title,type,items,subtitle){ return `<div class="admin-list"><div class="list-head"><h2>${title}</h2><button class="primary" data-create="${type}">＋ Create new</button></div>${items.sort((a,b)=>a.order-b.order).map(i=>`<article class="admin-row" data-id="${esc(i.id)}"><div><strong>${esc(i.title||i.name||i.label||i.type)}</strong><small>${esc(subtitle(i))}</small></div><span class="status ${i.visible?'visible':'hidden'}">${i.visible?'Visible':'Hidden'}</span><div class="row-actions"><button data-action="up">↑</button><button data-action="down">↓</button><button data-action="toggle">${i.visible?'◉':'○'}</button><button data-action="edit">✎</button><button class="danger-icon" data-action="delete">⌫</button></div></article>`).join('')}</div>`; }
function settings(){ const keys=['brandName','shortName','tagline','whatsappNumber','supportPhone','supportEmail','logoUrl','heroImage','footerText','instagramUrl','facebookUrl','currency']; return `<form class="editor-panel embedded" id="settings-form"><div class="form-grid">${keys.map(k=>field(k,k.replace(/([A-Z])/g,' $1'),data.settings[k]||'','text',['tagline','footerText'].includes(k))).join('')}${field('primaryColor','Primary color',data.settings.primaryColor,'color')}${field('accentColor','Accent color',data.settings.accentColor,'color')}</div><div class="editor-actions"><button class="primary">Save settings</button></div></form>`; }
function backup(){ return `<div class="data-tools"><article><span>⇩</span><div><h3>Export complete backup</h3><p>Download packages, settings and layout as JSON.</p></div><button id="export">Export JSON</button></article><article><span>⇧</span><div><h3>Import backup</h3><p>Replace this browser draft with a JSON backup.</p></div><button id="import">Import JSON</button><input id="import-file" hidden type="file" accept="application/json"></article><article><span>↻</span><div><h3>Reset seed data</h3><p>Restore the complete Canal, Marina, Yacht and Safari data.</p></div><button class="danger" id="reset">Reset</button></article></div>`; }
function content(){ if(tab==='packages')return packages(); if(tab==='categories')return genericList('Categories','category',data.categories,i=>`${i.kind} · ${data.packages.filter(p=>p.categoryId===i.id).length} packages`); if(tab==='addons')return genericList('Add-ons','addon',data.addOns,i=>`AED ${i.price} · ${i.unit}`); if(tab==='sections')return genericList('Page sections','section',data.sections,i=>`${i.type} · position ${i.order}`); if(tab==='navigation')return genericList('Navigation links','nav',data.navLinks,i=>i.href); if(tab==='settings')return settings(); return backup(); }
function render(){ document.documentElement.style.setProperty('--primary',data.settings.primaryColor||'#2563eb'); document.documentElement.style.setProperty('--accent',data.settings.accentColor||'#d6a756'); root.innerHTML=`${sidebar()}<section class="admin-main">${topbar()}${content()}</section><div id="drawer"></div>`; bind(); }

function field(name,label,value,type='text',wide=false,options=[]){ if(type==='textarea')return `<label class="${wide?'wide':''}">${label}<textarea name="${name}">${esc(value)}</textarea></label>`; if(type==='select')return `<label class="${wide?'wide':''}">${label}<select name="${name}">${options.map(o=>{const val=typeof o==='string'?o:o[0],txt=typeof o==='string'?o:o[1];return `<option value="${esc(val)}" ${String(val)===String(value)?'selected':''}>${esc(txt)}</option>`;}).join('')}</select></label>`; if(type==='checkbox')return `<label class="toggle"><input type="checkbox" name="${name}" ${value?'checked':''}>${label}</label>`; return `<label class="${wide?'wide':''}">${label}<input type="${type}" name="${name}" value="${esc(value)}"></label>`; }
function heading(text){return `<h3 class="wide cms-form-heading">${esc(text)}</h3>`;}
function emptyPackage(){return {id:uid('package'),title:'New Package',slug:`new-package-${Date.now()}`,categoryId:data.categories[0]?.id||'canal',level:'Standard',status:'Draft',bookingMode:'Per person',priceUnit:'per adult',originalPrice:0,offerPrice:0,adultPrice:0,childPrice:0,childAgePolicy:'',infantPolicy:'',image:'',gallery:[],location:'',boardingLocation:'',mapUrl:'',meetingInstructions:'',pickupDetails:'',dropoffDetails:'',boatName:'',boatType:'',duration:'',availableDays:'Daily',capacity:'',minimumGuests:1,maximumGuests:0,seating:'',upperDeckDetails:'',lowerDeckDetails:'',acDetails:'',shortDescription:'',description:'',buffetDetails:'',drinks:'',entertainment:'',views:[],highlights:[],inclusions:[],exclusions:[],importantNotes:[],landmarks:[],timeSlots:[],parkingInfo:'',paymentMethod:'',cancellationPolicy:'',bestSuitedFor:'',faqs:[],addOnIds:[],badges:[],rating:0,reviewCount:0,whatsappMessage:'',seoTitle:'',metaDescription:'',internalNotes:'',featured:false,visible:true,order:data.packages.length+1};}
function packageFields(p){ const cats=data.categories.map(c=>[c.id,c.name]); return heading('Basic information')+field('title','Package title',p.title)+field('slug','URL slug',p.slug)+`<label>Category<select name="categoryId">${cats.map(([id,name])=>`<option value="${esc(id)}" ${id===p.categoryId?'selected':''}>${esc(name)}</option>`).join('')}</select></label>`+field('level','Package level',p.level,'select',false,PACKAGE_LEVELS)+field('status','Content status',p.status||'Published','select',false,['Draft','Published','Hidden','Sold Out'])+field('bookingMode','Booking mode',p.bookingMode||'Per person')+field('priceUnit','Price unit',p.priceUnit||'per adult')+field('visible','Visible on website',p.visible,'checkbox')+field('featured','Featured package',p.featured,'checkbox')+
 heading('Pricing and guest policy')+field('originalPrice','Original price',p.originalPrice||0,'number')+field('offerPrice','Offer price',p.offerPrice||0,'number')+field('adultPrice','Adult price',p.adultPrice||0,'number')+field('childPrice','Child price',p.childPrice||0,'number')+field('childAgePolicy','Child age policy',p.childAgePolicy||'','textarea')+field('infantPolicy','Infant policy',p.infantPolicy||'','textarea')+field('minimumGuests','Minimum guests',p.minimumGuests||0,'number')+field('maximumGuests','Maximum guests',p.maximumGuests||0,'number')+
 heading('Images and location')+field('image','Main image URL',p.image||'','text',true)+field('gallery','Gallery URLs, one per line',join(p.gallery),'textarea',true)+field('location','Cruise / activity location',p.location||'')+field('boardingLocation','Boarding / meeting location',p.boardingLocation||'')+field('mapUrl','Google Maps URL',p.mapUrl||'','text',true)+field('meetingInstructions','Meeting instructions',p.meetingInstructions||'','textarea',true)+field('pickupDetails','Pickup details',p.pickupDetails||'','textarea')+field('dropoffDetails','Drop-off details',p.dropoffDetails||'','textarea')+
 heading('Boat and operations')+field('boatName','Boat / vehicle name',p.boatName||'')+field('boatType','Boat / activity type',p.boatType||'')+field('duration','Duration',p.duration||'')+field('availableDays','Available days',p.availableDays||'Daily')+field('capacity','Maximum capacity',p.capacity||'')+field('seating','Seating type',p.seating||'','textarea')+field('upperDeckDetails','Upper-deck details',p.upperDeckDetails||'','textarea')+field('lowerDeckDetails','Lower-deck details',p.lowerDeckDetails||'','textarea')+field('acDetails','Air-conditioning details',p.acDetails||'','textarea')+field('timeSlots','Time slots: Label | Boarding | Sailing | Return | Days',slotsText(p.timeSlots),'textarea',true)+
 heading('Public content')+field('shortDescription','Card description',p.shortDescription||'','textarea',true)+field('description','Full package description',p.description||'','textarea',true)+field('buffetDetails','Buffet / food details',p.buffetDetails||'','textarea')+field('drinks','Drinks',p.drinks||'','textarea')+field('entertainment','Entertainment',p.entertainment||'','textarea')+field('views','Views, one per line',join(p.views),'textarea')+field('highlights','Highlights, one per line',join(p.highlights),'textarea')+field('landmarks','Route landmarks, one per line',join(p.landmarks),'textarea')+field('inclusions','Included items, one per line',join(p.inclusions),'textarea')+field('exclusions','Excluded items, one per line',join(p.exclusions),'textarea')+field('importantNotes','Important notes, one per line',join(p.importantNotes||p.notes),'textarea')+
 heading('Policies, FAQs and booking')+field('parkingInfo','Parking information',p.parkingInfo||'','textarea')+field('paymentMethod','Payment method',p.paymentMethod||'','textarea')+field('cancellationPolicy','Cancellation policy',p.cancellationPolicy||'','textarea')+field('bestSuitedFor','Best suited for',p.bestSuitedFor||'','textarea')+field('faqs','FAQs: Question | Answer',faqText(p.faqs),'textarea',true)+field('whatsappMessage','WhatsApp booking message',p.whatsappMessage||'','textarea',true)+
 heading('Badges, SEO and internal')+field('badges','Badges, one per line',join(p.badges),'textarea')+field('rating','Rating',p.rating||0,'number')+field('reviewCount','Review count',p.reviewCount||0,'number')+field('seoTitle','SEO title',p.seoTitle||'')+field('metaDescription','Meta description',p.metaDescription||'','textarea',true)+field('internalNotes','Internal notes',p.internalNotes||'','textarea',true)+`<fieldset class="wide"><legend>Available add-ons</legend><div class="checkbox-grid">${data.addOns.map(a=>`<label><input type="checkbox" name="addon" value="${esc(a.id)}" ${(p.addOnIds||[]).includes(a.id)?'checked':''}>${esc(a.name)} · AED ${a.price}</label>`).join('')}</div></fieldset>`; }
function genericConfig(type){ if(type==='category')return {key:'categories',empty:{id:uid('category'),name:'New Category',slug:`category-${Date.now()}`,kind:'cruise',description:'',image:'',visible:true,order:data.categories.length+1}}; if(type==='addon')return {key:'addOns',empty:{id:uid('addon'),name:'New Add-on',price:0,unit:'per person',description:'',image:'',visible:true,order:data.addOns.length+1}}; if(type==='section')return {key:'sections',empty:{id:uid('section'),type:'custom',title:'New Section',subtitle:'',content:'',visible:true,order:data.sections.length+1}}; return {key:'navLinks',empty:{id:uid('nav'),label:'New Link',href:'#',visible:true,order:data.navLinks.length+1}}; }
function openEditor(type,item){ const p=structuredClone(item); let fields=''; if(type==='package')fields=packageFields(p); else if(type==='category')fields=field('name','Name',p.name)+field('slug','Slug',p.slug)+field('kind','Kind',p.kind,'select',false,['cruise','yacht','safari'])+field('image','Image URL',p.image,'text',true)+field('description','Description',p.description,'textarea',true)+field('visible','Visible',p.visible,'checkbox'); else if(type==='addon')fields=field('name','Name',p.name)+field('price','Price',p.price,'number')+field('unit','Unit',p.unit)+field('image','Image URL',p.image||'','text',true)+field('description','Description',p.description,'textarea',true)+field('visible','Visible',p.visible,'checkbox'); else if(type==='section')fields=field('title','Title',p.title)+field('type','Type',p.type,'select',false,['header','hero','categories','packages','trust','cta','custom','footer'])+field('subtitle','Subtitle',p.subtitle,'textarea',true)+field('content','Custom HTML',p.content||'','textarea',true)+field('visible','Visible',p.visible,'checkbox'); else fields=field('label','Label',p.label)+field('href','Link / anchor',p.href)+field('visible','Visible',p.visible,'checkbox'); document.querySelector('#drawer').innerHTML=`<div class="editor-panel"><div class="editor-head"><div><span class="eyebrow">Complete CMS editor</span><h2>${type==='package'?esc(p.title):`Edit ${esc(type)}`}</h2></div><button id="close">Close</button></div><form id="item-form"><div class="form-grid">${fields}</div><div class="editor-actions"><button type="button" class="secondary" id="cancel">Cancel</button><button class="primary">Save item</button></div></form></div>`; document.querySelector('#close').onclick=document.querySelector('#cancel').onclick=()=>document.querySelector('#drawer').innerHTML=''; document.querySelector('#item-form').onsubmit=e=>saveEditor(e,type,p); }
function saveEditor(e,type,draft){ e.preventDefault(); const form=new FormData(e.currentTarget); const next={...draft}; for(const [k,v] of form.entries()){if(k==='addon')continue; next[k]=['originalPrice','offerPrice','adultPrice','childPrice','minimumGuests','maximumGuests','rating','reviewCount','price'].includes(k)?Number(v):v;} ['visible','featured'].forEach(k=>{if(k in next)next[k]=form.has(k);}); if(type==='package'){['gallery','views','highlights','landmarks','inclusions','exclusions','importantNotes','badges'].forEach(k=>next[k]=lines(form.get(k))); next.timeSlots=slotsParse(form.get('timeSlots'));next.faqs=faqParse(form.get('faqs'));next.addOnIds=form.getAll('addon');next.notes=next.importantNotes;} const cfg=type==='package'?{key:'packages'}:genericConfig(type);const list=data[cfg.key];const i=list.findIndex(x=>x.id===next.id);if(i>=0)list[i]=next;else list.push(next);document.querySelector('#drawer').innerHTML='';persist(`${type} saved`); }
function bind(){ document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();}); document.querySelector('#save-all').onclick=()=>persist('All changes saved'); document.querySelectorAll('[data-create]').forEach(b=>b.onclick=()=>openEditor(b.dataset.create,b.dataset.create==='package'?emptyPackage():genericConfig(b.dataset.create).empty)); document.querySelector('#package-search')?.addEventListener('input',e=>{search=e.target.value.toLowerCase();render();}); document.querySelector('#category-filter')?.addEventListener('change',e=>{categoryFilter=e.target.value;render();}); const map={packages:['package','packages'],categories:['category','categories'],addons:['addon','addOns'],sections:['section','sections'],navigation:['nav','navLinks']}; if(map[tab])document.querySelectorAll('.admin-row').forEach(row=>row.onclick=e=>rowAction(e,row,...map[tab])); document.querySelector('#settings-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);for(const k of Object.keys(data.settings))if(f.has(k))data.settings[k]=f.get(k);persist('Settings saved');}); document.querySelector('#export')?.addEventListener('click',()=>downloadBackup(data));document.querySelector('#import')?.addEventListener('click',()=>document.querySelector('#import-file').click());document.querySelector('#import-file')?.addEventListener('change',async e=>{try{data=JSON.parse(await e.target.files[0].text());persist('Backup imported');}catch{alert('Invalid JSON file.');}});document.querySelector('#reset')?.addEventListener('click',()=>{if(confirm('Reset all CMS data?')){data=resetData();render();}}); }
function rowAction(e,row,type,key){const action=e.target.closest('[data-action]')?.dataset.action;if(!action)return;const list=data[key],i=list.findIndex(x=>x.id===row.dataset.id);if(i<0)return;const item=list[i];if(action==='edit')return openEditor(type,item);if(action==='preview'){window.open(`/package.html?slug=${encodeURIComponent(item.slug)}`,'_blank');return;}if(action==='delete'){if(confirm(`Delete ${item.title||item.name||item.label}?`)){list.splice(i,1);persist('Item deleted');}return;}if(action==='toggle'){item.visible=!item.visible;item.status=item.visible?'Published':'Hidden';persist(item.visible?'Item visible':'Item hidden');return;}if(action==='duplicate'){const copy=structuredClone(item);copy.id=uid(type);copy.title=`${copy.title} Copy`;copy.slug=`${copy.slug}-copy`;copy.order=list.length+1;list.push(copy);persist('Package duplicated');return;}const target=action==='up'?i-1:i+1;if(target>=0&&target<list.length){[list[i],list[target]]=[list[target],list[i]];list.forEach((x,n)=>x.order=n+1);persist('Order updated');}}
render();
